version: '3.9'

services:
  db:
    image: postgres:17.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vpnuser!23
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - redis_data:/data

volumes:
  database:
  redis_data:
